<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wmux.Tests\**" />
    <Content Remove="wmux.Tests\**" />
    <EmbeddedResource Remove="wmux.Tests\**" />
    <None Remove="wmux.Tests\**" />
  </ItemGroup>

</Project>
